plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.presage'
version = '0.1.0'

android {
  namespace "expo.modules.presage"

  compileSdk 36
  compileSdkMinor 1

  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }

  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation("com.presagetech:smartspectra:3.3.0")
  compileOnly("androidx.lifecycle:lifecycle-livedata-core:2.10.0")
  implementation("androidx.camera:camera-view:1.6.0")
}